[project]
channels = ["pytorch", "dglteam", "nvidia", "conda-forge"]
name = "graphland-baselines"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.11,<3.12"

[pypi-dependencies]
pandas = ">=2.3.1,<3"
scikit-learn = ">=1.7.1,<2"
jupyterlab = ">=4.4.6,<5"
ipywidgets = ">=8.1.7,<9"
matplotlib = ">=3.9.1,<4"
tqdm = ">=4.67.1,<5"
pydantic = ">=2.11.7,<3"
torch = "==2.1.0"
dgl = ">=2.1.0, <3"
torch-geometric = ">=2.6.1, <3"
torchdata = "<=0.7.0"
numpy = "<2"
torchmetrics = ">=1.8.1, <2"
terminaltables = ">=3.1.10, <4"
fastargs = { git = "https://github.com/Phoveran/fastargs.git", rev = "main" }
neptune = ">=1.14.0, <2"
triton = ">=2.1.0, <3"
ogb = ">=1.3.6, <2"
torch_scatter = { url = "https://data.pyg.org/whl/torch-2.1.0+cu121/torch_scatter-2.1.2+pt21cu121-cp311-cp311-linux_x86_64.whl" }
torch_sparse = { url = "https://data.pyg.org/whl/torch-2.1.0+cu121/torch_sparse-0.6.18+pt21cu121-cp311-cp311-linux_x86_64.whl" }
torch_cluster = { url = "https://data.pyg.org/whl/torch-2.1.0+cu121/torch_cluster-1.6.3+pt21cu121-cp311-cp311-linux_x86_64.whl" }
delu = ">=0.0.26, <0.0.27"
loguru = ">=0.7.3, <0.8"
tomli = ">=2.3.0, <3"
tomli-w = ">=1.2.0, <2"
optuna = ">=4.5.0, <5"
lightgbm = "==3.3.5"
